### ISSUE TITLE
'Internal server error' on API calls for certain countries

### ISSUE THREAD

**Issue by dalepotter** [IATI/iati-datastore#234]
The issue is found to affect Afghanistan and Pakistan, although other countries may be affected too:
http://datastore.iatistandard.org/api/1/access/activity.csv?recipient-country=AF
http://datastore.iatistandard.org/api/1/access/activity.csv?recipient-country=PK

**Comment by dalepotter** [comment]
Further information on diagnosis of this one - output from the apache error log:
```
[Thu Apr 16 18:27:05 2015] [error] ERROR:iatilib.frontend:Exception on /api/1/access/activity.csv [GET]
[Thu Apr 16 18:27:05 2015] [error] Traceback (most recent call last):
[Thu Apr 16 18:27:05 2015] [error]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
[Thu Apr 16 18:27:05 2015] [error]     response = self.full_dispatch_request()
[Thu Apr 16 18:27:05 2015] [error]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
[Thu Apr 16 18:27:05 2015] [error]     rv = self.handle_user_exception(e)
[Thu Apr 16 18:27:05 2015] [error]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
[Thu Apr 16 18:27:05 2015] [error]     reraise(exc_type, exc_value, tb)
[Thu Apr 16 18:27:05 2015] [error]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
[Thu Apr 16 18:27:05 2015] [error]     rv = self.dispatch_request()
[Thu Apr 16 18:27:05 2015] [error]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
[Thu Apr 16 18:27:05 2015] [error]     return self.view_functions[rule.endpoint](**req.view_args)
[Thu Apr 16 18:27:05 2015] [error]   File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 84, in view
[Thu Apr 16 18:27:05 2015] [error]     return self.dispatch_request(*args, **kwargs)
[Thu Apr 16 18:27:05 2015] [error]   File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 149, in dispatch_request
[Thu Apr 16 18:27:05 2015] [error]     return meth(*args, **kwargs)
[Thu Apr 16 18:27:05 2015] [error]   File "/home/datastore/iati-datastore/iati_datastore/iatilib/frontend/api1.py", line 221, in get
[Thu Apr 16 18:27:05 2015] [error]     return self.get_response(*forms[format])
[Thu Apr 16 18:27:05 2015] [error]   File "/home/datastore/iati-datastore/iati_datastore/iatilib/frontend/api1.py", line 205, in get_response
[Thu Apr 16 18:27:05 2015] [error]     body = u"".join(serializer(pagination))
[Thu Apr 16 18:27:05 2015] [error]   File "/home/datastore/iati-datastore/iati_datastore/iatilib/frontend/serialize/csv.py", line 357, in __call__
[Thu Apr 16 18:27:05 2015] [error]     row = [accessor(obj) for accessor in self.fields_by_major_version[get_major_version(obj)].values()]
[Thu Apr 16 18:27:05 2015] [error]   File "/home/datastore/iati-datastore/iati_datastore/iatilib/frontend/serialize/csv.py", line 12, in accessor
[Thu Apr 16 18:27:05 2015] [error]     if len(set(t.value.currency for t in getattr(activity, column))) > 1:
[Thu Apr 16 18:27:05 2015] [error]   File "/home/datastore/iati-datastore/iati_datastore/iatilib/model.py", line 79, in __get__
[Thu Apr 16 18:27:05 2015] [error]     return [t for t in obj.transactions if t.type.value in self.type_codes]
[Thu Apr 16 18:27:05 2015] [error] AttributeError: 'NoneType' object has no attribute 'value'
```

**Comment by dalepotter** [comment]
A workaround for downloading this data is to query for the XML version instead: 
http://datastore.iatistandard.org/api/1/access/activity.xml?recipient-country=AF
http://datastore.iatistandard.org/api/1/access/activity.xml?recipient-country=PK

**Comment by dalepotter** [comment]
This error seems to arise due to missing transaction-type codes - i.e. ```transaction-type code=""``` for data affecting Afghanistan and Pakistan.
